=== Datenverlust/SemanticDecompositionExperiments/SemanticDistanceMeasures/Measures/src/test/resources/roget_elkb/1911/heads/heads.dtd
<?xml version="1.0" encoding="iso-8859-1" ?>

<!--
  ~ Copyright (C) Johannes Fähndrich - All Rights Reserved.
  ~ Unauthorized copying of this file, via any medium is strictly
  ~ prohibited Proprietary and confidential.
  ~ Written by Johannes Fähndrich <faehndrich@gmail.com.com>,  2011
  ~
  -->

<!ELEMENT head (pos+)>
<!ATTLIST head number CDATA #REQUIRED name CDATA #REQUIRED origNum CDATA #REQUIRED class CDATA #REQUIRED section CDATA #REQUIRED subSection CDATA #REQUIRED headGroup CDATA #REQUIRED>

<!ELEMENT pos (paragraph+)>
<!ATTLIST pos number CDATA #REQUIRED type (N.|VB.|ADJ.|ADV.|INT.|PHR.|PREF.|PRON.) #REQUIRED>

<!ELEMENT paragraph (sg+)>
<!ATTLIST paragraph number CDATA #REQUIRED name CDATA #REQUIRED>

<!ELEMENT sg (word+)>
<!ATTLIST sg number CDATA #REQUIRED>

<!ELEMENT word (#PCDATA)>
<!ATTLIST word number CDATA #REQUIRED paraRef CDATA #IMPLIED posRef CDATA #IMPLIED headRef CDATA #IMPLIED>

=== Datenverlust/SemanticDecompositionExperiments/DataSet/src/main/resources/roget_elkb/1911X1/heads/head421.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!--
  ~ Copyright (C) Johannes Fähndrich - All Rights Reserved.
  ~ Unauthorized copying of this file, via any medium is strictly
  ~ prohibited Proprietary and confidential.
  ~ Written by Johannes Fähndrich <faehndrich@gmail.com.com>,  2011
  ~
  -->

<!DOCTYPE head SYSTEM "heads.dtd">
<?xml-stylesheet href="rogets.xsl" type="text/xsl" ?>

<head number="421" name="Loudness" origNum="#404." class="3" section="3" subSection="2" headGroup="19">
	<pos number="1" type="N.">
		<paragraph number="1" name="loudness">
			<sg number="1">
				<word number="1">loudness</word>
				<word number="2">power</word>
			</sg>
			<sg number="2">
				<word number="1">loud noise</word>
				<word number="2">din</word>
			</sg>
			<sg number="3">
				<word number="1">blare</word>
			</sg>
			<sg number="4">
				<word number="1">clang</word>
				<word number="2">clangor</word>
			</sg>
			<sg number="5">
				<word number="1">clatter</word>
				<word number="2">noise</word>
				<word number="3">bombilation</word>
				<word number="4">roar</word>
				<word number="5">uproar</word>
				<word number="6">racket</word>
				<word number="7">hubbub</word>
				<word number="8">bobbery</word>
				<word number="9">fracas</word>
				<word number="10">charivari</word>
				<word number="11">trumpet blast</word>
				<word number="12">flourish of trumpets</word>
				<word number="13">fanfare</word>
				<word number="14">tintamarre</word>
				<word number="15">peal</word>
				<word number="16">swell</word>
				<word number="17">blast</word>
				<word number="18">larum</word>
				<word number="19">boom</word>
			</sg>
			<sg number="6">
				<word number="1" paraRef="explosion" headRef="423">bang</word>
			</sg>
			<sg number="7">
				<word number="1" paraRef="resonance" headRef="425">resonance</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="vociferation">
			<sg number="1">
				<word number="1">vociferation</word>
				<word number="2" paraRef="hullabaloo" headRef="429">hullabaloo</word>
			</sg>
			<sg number="2">
				<word number="1">lungs</word>
			</sg>
			<sg number="3">
				<word number="1">Stentor. artillery</word>
				<word number="2">cannon</word>
			</sg>
			<sg number="4">
				<word number="1">thunder</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="2" type="VB.">
		<paragraph number="1" name="be loud">
			<sg number="1">
				<word number="1" paraRef="" posRef="adj.">be loud</word>
			</sg>
			<sg number="2">
				<word number="1">peal</word>
				<word number="2">swell</word>
				<word number="3">clang</word>
				<word number="4">boom</word>
				<word number="5">thunder</word>
				<word number="6">blare</word>
				<word number="7">fulminate</word>
				<word number="8">roar</word>
				<word number="9" new="1">chime</word>
			</sg>
			<sg number="3">
				<word number="1" paraRef="resound" headRef="425">resound</word>
				<word number="2" paraRef="vociferate" headRef="429">shout</word>
			</sg>
			<sg number="4">
				<word number="1" paraRef="cry" headRef="430">bellow</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="rend the air">
			<sg number="1">
				<word number="1">rend the air</word>
				<word number="2">rend the skies</word>
			</sg>
			<sg number="2">
				<word number="1">fill the air</word>
			</sg>
			<sg number="3">
				<word number="1">din in the ear</word>
				<word number="2">ring in the ear</word>
				<word number="3">thunder in the ear</word>
			</sg>
			<sg number="4">
				<word number="1">pierce the ears</word>
				<word number="2">split the ears</word>
				<word number="3">rend the ears</word>
				<word number="4">split the head</word>
			</sg>
			<sg number="5">
				<word number="1">deafen</word>
				<word number="2">stun</word>
			</sg>
			<sg number="6">
				<word number="1">faire le diable a quatre</word>
			</sg>
			<sg number="7">
				<word number="1">make one's windows shake</word>
				<word number="2">rattle the windows</word>
			</sg>
			<sg number="8">
				<word number="1">awaken the echoes</word>
				<word number="2">startle the echoes</word>
			</sg>
			<sg number="9">
				<word number="1">wake the dead</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="3" type="ADJ.">
		<paragraph number="1" name="loud">
			<sg number="1">
				<word number="1">loud</word>
				<word number="2">sonorous</word>
			</sg>
			<sg number="2">
				<word number="1">high-sounding</word>
				<word number="2">big-sounding</word>
			</sg>
			<sg number="3">
				<word number="1">deep</word>
				<word number="2">full</word>
				<word number="3">powerful</word>
				<word number="4">noisy</word>
				<word number="5">blatant</word>
				<word number="6">clangorous</word>
				<word number="7">multisonous</word>
			</sg>
			<sg number="4">
				<word number="1">thundering</word>
				<word number="2" paraRef="" posRef="v.">deafening</word>
			</sg>
			<sg number="5">
				<word number="1">trumpet-tongued</word>
			</sg>
			<sg number="6">
				<word number="1">ear-splitting</word>
				<word number="2">ear-rending</word>
				<word number="3">ear- deafening</word>
			</sg>
			<sg number="7">
				<word number="1">piercing</word>
			</sg>
			<sg number="8">
				<word number="1">obstreperous</word>
				<word number="2">rackety</word>
				<word number="3">uproarious</word>
			</sg>
			<sg number="9">
				<word number="1">enough to wake the dead</word>
				<word number="2">enough to wake seven sleepers</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="shrill">
			<sg number="1">
				<word number="1" paraRef="shrill" headRef="428">shrill</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="vociferous" headRef="429">clamorous</word>
			</sg>
			<sg number="3">
				<word number="1">stentorian</word>
				<word number="2">stentorophonic</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="4" type="ADV.">
		<paragraph number="1" name="loudly">
			<sg number="1">
				<word number="1" paraRef="" posRef="adj.">loudly</word>
			</sg>
			<sg number="2">
				<word number="1">at the top of one's voice</word>
				<word number="2">at the top of one's  lungs</word>
				<word number="3">lustily</word>
				<word number="4">in full cry</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="6" type="PHR.">
		<paragraph number="1" name="the air rings with">
			<sg number="1">
				<word number="1">the air rings with</word>
			</sg>
			<sg number="2">
				<word number="1">"the deep dread-bolted thunder"</word>
			</sg>
		</paragraph>
	</pos>
</head>

=== Datenverlust/SemanticDecompositionExperiments/DataSet/src/main/resources/roget_elkb/1911X5/heads/head1031.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!--
  ~ Copyright (C) Johannes Fähndrich - All Rights Reserved.
  ~ Unauthorized copying of this file, via any medium is strictly
  ~ prohibited Proprietary and confidential.
  ~ Written by Johannes Fähndrich <faehndrich@gmail.com.com>,  2011
  ~
  -->

<!DOCTYPE head SYSTEM "heads.dtd">
<?xml-stylesheet href="rogets.xsl" type="text/xsl" ?>

<head number="1031" name="Piety" origNum="#987." class="8" section="5" subSection="3" headGroup="1">
	<pos number="1" type="N.">
		<paragraph number="1" name="piety">
			<sg number="1">
				<word number="1">piety</word>
				<word number="2">religion</word>
				<word number="3">theism</word>
				<word number="4">faith</word>
			</sg>
			<sg number="2">
				<word number="1">religiousness</word>
				<word number="2" paraRef="" posRef="adj.">holiness</word>
			</sg>
			<sg number="3">
				<word number="1">saintship</word>
			</sg>
			<sg number="4">
				<word number="1">religionism</word>
			</sg>
			<sg number="5">
				<word number="1" paraRef="sanctimony" headRef="1032">assumed piety</word>
			</sg>
			<sg number="6">
				<word number="1" paraRef="respect" headRef="970">reverence</word>
			</sg>
			<sg number="7">
				<word number="1">humility</word>
				<word number="2">veneration</word>
				<word number="3">devotion</word>
			</sg>
			<sg number="8">
				<word number="1" paraRef="worship" headRef="1034">prostration</word>
			</sg>
			<sg number="9">
				<word number="1">grace</word>
				<word number="2">unction</word>
				<word number="3">edification</word>
			</sg>
			<sg number="10">
				<word number="1">sanctity</word>
				<word number="2">sanctitude</word>
			</sg>
			<sg number="11">
				<word number="1">consecration</word>
			</sg>
			<sg number="12">
				<word number="1" new="1">asceticism</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="spiritual existence">
			<sg number="1">
				<word number="1">spiritual existence</word>
				<word number="2">odor of sanctity</word>
				<word number="3">beauty of holiness</word>
			</sg>
		</paragraph>
		<paragraph number="3" name="theopathy">
			<sg number="1">
				<word number="1">theopathy</word>
				<word number="2">beatification</word>
				<word number="3">adoption</word>
				<word number="4">regeneration</word>
				<word number="5">conversion</word>
				<word number="6">justification</word>
				<word number="7">sanctification</word>
				<word number="8">salvation</word>
				<word number="9">inspiration</word>
				<word number="10">bread of life</word>
			</sg>
			<sg number="2">
				<word number="1">Body and Blood of Christ</word>
			</sg>
		</paragraph>
		<paragraph number="4" name="believer">
			<sg number="1">
				<word number="1">believer</word>
				<word number="2">convert</word>
				<word number="3">theist</word>
				<word number="4">Christian</word>
				<word number="5">devotee</word>
				<word number="6">pietist</word>
			</sg>
			<sg number="2">
				<word number="1">the good</word>
				<word number="2">the righteous</word>
				<word number="3">the just</word>
				<word number="4">the believing</word>
				<word number="5">the elect</word>
			</sg>
			<sg number="3">
				<word number="1">Saint</word>
				<word number="2">Madonna</word>
				<word number="3">Notre Dame</word>
				<word number="4">Our Lady</word>
			</sg>
		</paragraph>
		<paragraph number="5" name="the children of God">
			<sg number="1">
				<word number="1">the children of God</word>
				<word number="2">the children of the Kingdom</word>
				<word number="3">the children of the light</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="2" type="VB.">
		<paragraph number="1" name="be pious">
			<sg number="1">
				<word number="1" paraRef="" posRef="adj.">be pious</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="" posRef="n.">have faith</word>
			</sg>
			<sg number="3">
				<word number="1">believe</word>
				<word number="2">receive Christ</word>
			</sg>
			<sg number="4">
				<word number="1" paraRef="revere" headRef="970">revere</word>
			</sg>
			<sg number="5">
				<word number="1">be converted</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="convert">
			<sg number="1">
				<word number="1">convert</word>
				<word number="2">edify</word>
				<word number="3">sanctify</word>
				<word number="4">keep holy</word>
				<word number="5">beatify</word>
				<word number="6">regenerate</word>
				<word number="7">inspire</word>
				<word number="8">consecrate</word>
				<word number="9">enshrine</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="3" type="ADJ.">
		<paragraph number="1" name="pious">
			<sg number="1">
				<word number="1">pious</word>
				<word number="2">religious</word>
				<word number="3">devout</word>
				<word number="4">devoted</word>
				<word number="5">reverent</word>
				<word number="6">godly</word>
				<word number="7">heavenly- minded</word>
				<word number="8">humble</word>
				<word number="9">pure</word>
				<word number="10">holy</word>
				<word number="11">spiritual</word>
				<word number="12">pietistic</word>
			</sg>
			<sg number="2">
				<word number="1">saintly</word>
				<word number="2">saint-like</word>
			</sg>
			<sg number="3">
				<word number="1">seraphic</word>
				<word number="2">sacred</word>
				<word number="3">solemn</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="believing">
			<sg number="1">
				<word number="1">believing</word>
				<word number="2">faithful</word>
				<word number="3">Christian</word>
				<word number="4">Catholic</word>
			</sg>
		</paragraph>
		<paragraph number="3" name="elected">
			<sg number="1">
				<word number="1">elected</word>
				<word number="2">adopted</word>
				<word number="3">justified</word>
				<word number="4">sanctified</word>
				<word number="5">regenerated</word>
				<word number="6">inspired</word>
				<word number="7">consecrated</word>
				<word number="8">converted</word>
				<word number="9">unearthly</word>
				<word number="10">not of the earth</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="6" type="PHR.">
		<paragraph number="1" name="ne vile fano">
			<sg number="1">
				<word number="1">ne vile fano</word>
			</sg>
			<sg number="2">
				<word number="1">"pure-eyed Faith . . . thou hovering angel girt with golden wings"</word>
			</sg>
		</paragraph>
	</pos>
</head>

=== Datenverlust/SemanticDecompositionExperiments/SemanticDistanceMeasures/ELKB/src/main/resources/roget_elkb/1911/heads/head716.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!--
  ~ Copyright (C) Johannes Fähndrich - All Rights Reserved.
  ~ Unauthorized copying of this file, via any medium is strictly
  ~ prohibited Proprietary and confidential.
  ~ Written by Johannes Fähndrich <faehndrich@gmail.com.com>,  2011
  ~
  -->

<!DOCTYPE head SYSTEM "heads.dtd">

<head number="716" name="Repose" origNum="#687." class="6" section="3" subSection="1" headGroup="4">
	<pos number="1" type="N.">
		<paragraph number="1" name="repose">
			<sg number="1">
				<word number="1">repose</word>
				<word number="2">rest</word>
				<word number="3">silken repose</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="sleep" headRef="712">sleep</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="relaxation">
			<sg number="1">
				<word number="1">relaxation</word>
				<word number="2">breathing time</word>
			</sg>
			<sg number="2">
				<word number="1">halt</word>
				<word number="2">stay</word>
				<word number="3" paraRef="cessation" headRef="149">pause</word>
			</sg>
			<sg number="3">
				<word number="1">respite</word>
			</sg>
		</paragraph>
		<paragraph number="3" name="day of rest">
			<sg number="1">
				<word number="1">day of rest</word>
				<word number="2">dies non</word>
				<word number="3">Sabbath</word>
				<word number="4">Lord's day</word>
				<word number="5">holiday</word>
				<word number="6">red-letter day</word>
				<word number="7">vacation</word>
				<word number="8">recess</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="2" type="VB.">
		<paragraph number="1" name="repose">
			<sg number="1">
				<word number="1">repose</word>
			</sg>
			<sg number="2">
				<word number="1">rest</word>
				<word number="2">rest and be thankful</word>
			</sg>
			<sg number="3">
				<word number="1">take a rest</word>
				<word number="2">take one's ease</word>
				<word number="3">take it easy</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="relax">
			<sg number="1">
				<word number="1">relax</word>
				<word number="2">unbend</word>
				<word number="3">slacken</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="refresh" headRef="718">take breath</word>
			</sg>
			<sg number="3">
				<word number="1">rest upon one's oars</word>
			</sg>
			<sg number="4">
				<word number="1" paraRef="cease" headRef="149">pause</word>
			</sg>
			<sg number="5">
				<word number="1">stay one's hand</word>
			</sg>
		</paragraph>
		<paragraph number="3" name="lie down">
			<sg number="1">
				<word number="1">lie down</word>
			</sg>
			<sg number="2">
				<word number="1">recline</word>
				<word number="2">recline on a bed of down</word>
				<word number="3">recline on an easy chair</word>
			</sg>
			<sg number="3">
				<word number="1">go to rest</word>
				<word number="2">go to bed</word>
				<word number="3" paraRef="go to sleep" headRef="712">go to sleep</word>
			</sg>
		</paragraph>
		<paragraph number="4" name="take a holiday">
			<sg number="1">
				<word number="1">take a holiday</word>
				<word number="2">shut up shop</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="inaction" headRef="710">lie fallow</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="3" type="ADJ.">
		<paragraph number="1" name="reposing">
			<sg number="1">
				<word number="1" paraRef="" posRef="v.">reposing</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="" posRef="v.">relaxed</word>
			</sg>
			<sg number="3">
				<word number="1">unstrained</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="unstressed">
			<sg number="1">
				<word number="1">unstressed</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="4" type="ADV.">
		<paragraph number="1" name="at rest">
			<sg number="1">
				<word number="1">at rest</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="6" type="PHR.">
		<paragraph number="1" name="the best of men have ever loved repose">
			<sg number="1">
				<word number="1">"the best of men have ever loved repose"</word>
			</sg>
			<sg number="2">
				<word number="1">"to repair our nature with comforting repose"</word>
			</sg>
		</paragraph>
	</pos>
</head>

=== Datenverlust/SemanticDecompositionExperiments/DataSet/src/main/resources/roget_elkb/1911X1/heads/head306.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!--
  ~ Copyright (C) Johannes Fähndrich - All Rights Reserved.
  ~ Unauthorized copying of this file, via any medium is strictly
  ~ prohibited Proprietary and confidential.
  ~ Written by Johannes Fähndrich <faehndrich@gmail.com.com>,  2011
  ~
  -->

<!DOCTYPE head SYSTEM "heads.dtd">
<?xml-stylesheet href="rogets.xsl" type="text/xsl" ?>

<head number="306" name="Egress" origNum="#295." class="2" section="4" subSection="4" headGroup="9">
	<pos number="1" type="N.">
		<paragraph number="1" name="egress">
			<sg number="1">
				<word number="1">egress</word>
				<word number="2">exit</word>
				<word number="3">issue</word>
			</sg>
			<sg number="2">
				<word number="1">emersion</word>
				<word number="2">emergence</word>
			</sg>
			<sg number="3">
				<word number="1">outbreak</word>
				<word number="2">outburst</word>
			</sg>
			<sg number="4">
				<word number="1">eruption</word>
				<word number="2">proruption</word>
			</sg>
			<sg number="5">
				<word number="1">emanation</word>
			</sg>
			<sg number="6">
				<word number="1">egression</word>
			</sg>
			<sg number="7">
				<word number="1">evacuation</word>
			</sg>
			<sg number="8">
				<word number="1">exudation</word>
				<word number="2">transudation</word>
			</sg>
			<sg number="9">
				<word number="1">extravasation</word>
				<word number="2">perspiration</word>
				<word number="3">sweating</word>
				<word number="4">leakage</word>
				<word number="5">percolation</word>
				<word number="6">distillation</word>
				<word number="7">oozing</word>
			</sg>
			<sg number="10">
				<word number="1" paraRef="water in motion" headRef="359">gush</word>
			</sg>
			<sg number="11">
				<word number="1">outpour</word>
				<word number="2">outpouring</word>
			</sg>
			<sg number="12">
				<word number="1">effluence</word>
				<word number="2">effusion</word>
			</sg>
			<sg number="13">
				<word number="1">effluxion</word>
				<word number="2">drain</word>
			</sg>
			<sg number="14">
				<word number="1" paraRef="" posRef="v.">dribbling</word>
			</sg>
			<sg number="15">
				<word number="1">defluxion</word>
			</sg>
			<sg number="16">
				<word number="1">drainage</word>
			</sg>
			<sg number="17">
				<word number="1">outcome</word>
				<word number="2">output</word>
			</sg>
			<sg number="18">
				<word number="1" paraRef="excretion" headRef="310">discharge</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="export">
			<sg number="1">
				<word number="1">export</word>
				<word number="2">expatriation</word>
			</sg>
			<sg number="2">
				<word number="1">emigration</word>
				<word number="2">remigration</word>
			</sg>
			<sg number="3">
				<word number="1">debouch</word>
				<word number="2">debouche</word>
			</sg>
			<sg number="4">
				<word number="1">emunctory</word>
			</sg>
			<sg number="5">
				<word number="1" paraRef="departure" headRef="304">exodus</word>
			</sg>
			<sg number="6">
				<word number="1">emigrant</word>
			</sg>
		</paragraph>
		<paragraph number="3" name="outlet">
			<sg number="1">
				<word number="1">outlet</word>
				<word number="2">vent</word>
				<word number="3">spout</word>
				<word number="4">tap</word>
				<word number="5">sluice</word>
				<word number="6">floodgate</word>
			</sg>
			<sg number="2">
				<word number="1">pore</word>
			</sg>
			<sg number="3">
				<word number="1">vomitory</word>
				<word number="2">outgate</word>
				<word number="3">sally port</word>
			</sg>
			<sg number="4">
				<word number="1">way out</word>
			</sg>
			<sg number="5">
				<word number="1">mouth</word>
				<word number="2" paraRef="opening" headRef="271">door</word>
			</sg>
			<sg number="6">
				<word number="1" paraRef="way" headRef="656">path</word>
			</sg>
			<sg number="7">
				<word number="1" paraRef="conduit" headRef="361">conduit</word>
			</sg>
			<sg number="8">
				<word number="1" paraRef="airpipe" headRef="362">airpipe</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="2" type="VB.">
		<paragraph number="1" name="emerge">
			<sg number="1">
				<word number="1">emerge</word>
				<word number="2">emanate</word>
				<word number="3">issue</word>
			</sg>
			<sg number="2">
				<word number="1">egress</word>
			</sg>
			<sg number="3">
				<word number="1">go out of</word>
				<word number="2">come out of</word>
				<word number="3">move out of</word>
				<word number="4">pass out of</word>
				<word number="5">pour out of</word>
				<word number="6">flow out of</word>
			</sg>
			<sg number="4">
				<word number="1">pass out of</word>
				<word number="2">evacuate</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="exude">
			<sg number="1">
				<word number="1">exude</word>
				<word number="2">transude</word>
			</sg>
			<sg number="2">
				<word number="1">leak</word>
				<word number="2">run through</word>
				<word number="3">out through</word>
			</sg>
			<sg number="3">
				<word number="1">percolate</word>
				<word number="2">transcolate</word>
			</sg>
			<sg number="4">
				<word number="1">egurgitate</word>
			</sg>
			<sg number="5">
				<word number="1">strain</word>
				<word number="2">distill</word>
			</sg>
			<sg number="6">
				<word number="1">perspire</word>
				<word number="2">sweat</word>
				<word number="3">drain</word>
				<word number="4">ooze</word>
			</sg>
			<sg number="7">
				<word number="1">filter</word>
				<word number="2">filtrate</word>
			</sg>
			<sg number="8">
				<word number="1">dribble</word>
				<word number="2">gush</word>
				<word number="3">spout</word>
				<word number="4">flow out</word>
			</sg>
			<sg number="9">
				<word number="1">well</word>
				<word number="2">well out</word>
			</sg>
			<sg number="10">
				<word number="1">pour</word>
				<word number="2" paraRef="water in motion" headRef="359">trickle</word>
			</sg>
			<sg number="11">
				<word number="1">effuse</word>
				<word number="2">extravasate</word>
				<word number="3">disembogue</word>
				<word number="4">discharge itself</word>
				<word number="5">debouch</word>
			</sg>
			<sg number="12">
				<word number="1">come forth</word>
				<word number="2">break forth</word>
			</sg>
			<sg number="13">
				<word number="1">burst out</word>
				<word number="2">burst through</word>
			</sg>
			<sg number="14">
				<word number="1">find vent</word>
			</sg>
			<sg number="15">
				<word number="1" paraRef="escape" headRef="700">escape</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="3" type="ADJ.">
		<paragraph number="1" name="effused">
			<sg number="1">
				<word number="1" paraRef="" posRef="v.">effused</word>
			</sg>
			<sg number="2">
				<word number="1">outgoing</word>
			</sg>
		</paragraph>
	</pos>
</head>

=== Datenverlust/SemanticDecompositionExperiments/SemanticDistanceMeasures/Measures/src/test/resources/roget_elkb/1911X5/heads/head404.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!--
  ~ Copyright (C) Johannes Fähndrich - All Rights Reserved.
  ~ Unauthorized copying of this file, via any medium is strictly
  ~ prohibited Proprietary and confidential.
  ~ Written by Johannes Fähndrich <faehndrich@gmail.com.com>,  2011
  ~
  -->

<!DOCTYPE head SYSTEM "heads.dtd">
<?xml-stylesheet href="rogets.xsl" type="text/xsl" ?>

<head number="404" name="Taste" origNum="#390." class="3" section="3" subSection="2" headGroup="10">
	<pos number="1" type="N.">
		<paragraph number="1" name="taste">
			<sg number="1">
				<word number="1">taste</word>
				<word number="2">flavor</word>
				<word number="3">gust</word>
				<word number="4">gusto</word>
				<word number="5">savor</word>
			</sg>
			<sg number="2">
				<word number="1">gout</word>
				<word number="2">relish</word>
			</sg>
			<sg number="3">
				<word number="1">sapor</word>
				<word number="2">sapidity</word>
			</sg>
			<sg number="4">
				<word number="1">twang</word>
				<word number="2">smack</word>
				<word number="3">smatch</word>
			</sg>
			<sg number="5">
				<word number="1">aftertaste</word>
				<word number="2">tang</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="tasting">
			<sg number="1">
				<word number="1">tasting</word>
			</sg>
			<sg number="2">
				<word number="1">degustation</word>
				<word number="2">gustation</word>
			</sg>
		</paragraph>
		<paragraph number="3" name="palate">
			<sg number="1">
				<word number="1">palate</word>
				<word number="2">tongue</word>
				<word number="3">tooth</word>
				<word number="4">stomach</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="2" type="VB.">
		<paragraph number="1" name="taste">
			<sg number="1">
				<word number="1">taste</word>
				<word number="2">savor</word>
				<word number="3">smatch</word>
				<word number="4">smack</word>
				<word number="5">flavor</word>
				<word number="6">twang</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="savory" headRef="410">tickle the palate</word>
			</sg>
			<sg number="3">
				<word number="1">smack the lips</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="3" type="ADJ.">
		<paragraph number="1" name="sapid">
			<sg number="1">
				<word number="1">sapid</word>
				<word number="2">saporific</word>
			</sg>
			<sg number="2">
				<word number="1">gustable</word>
				<word number="2">gustatory</word>
			</sg>
			<sg number="3">
				<word number="1">gustful</word>
			</sg>
			<sg number="4">
				<word number="1">strong</word>
				<word number="2">gamy</word>
			</sg>
			<sg number="5">
				<word number="1" paraRef="palatable" headRef="410">palatable</word>
			</sg>
		</paragraph>
	</pos>
</head>
