=== Datenverlust/SemanticDecompositionExperiments/SemanticDistanceMeasures/Measures/src/test/resources/roget_elkb/1911/heads/heads.dtd
<?xml version="1.0" encoding="iso-8859-1" ?>

<!--
  ~ Copyright (C) Johannes Fähndrich - All Rights Reserved.
  ~ Unauthorized copying of this file, via any medium is strictly
  ~ prohibited Proprietary and confidential.
  ~ Written by Johannes Fähndrich <faehndrich@gmail.com.com>,  2011
  ~
  -->

<!ELEMENT head (pos+)>
<!ATTLIST head number CDATA #REQUIRED name CDATA #REQUIRED origNum CDATA #REQUIRED class CDATA #REQUIRED section CDATA #REQUIRED subSection CDATA #REQUIRED headGroup CDATA #REQUIRED>

<!ELEMENT pos (paragraph+)>
<!ATTLIST pos number CDATA #REQUIRED type (N.|VB.|ADJ.|ADV.|INT.|PHR.|PREF.|PRON.) #REQUIRED>

<!ELEMENT paragraph (sg+)>
<!ATTLIST paragraph number CDATA #REQUIRED name CDATA #REQUIRED>

<!ELEMENT sg (word+)>
<!ATTLIST sg number CDATA #REQUIRED>

<!ELEMENT word (#PCDATA)>
<!ATTLIST word number CDATA #REQUIRED paraRef CDATA #IMPLIED posRef CDATA #IMPLIED headRef CDATA #IMPLIED>

=== Datenverlust/SemanticDecompositionExperiments/DataSet/src/main/resources/roget_elkb/1911/heads/head466.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!--
  ~ Copyright (C) Johannes Fähndrich - All Rights Reserved.
  ~ Unauthorized copying of this file, via any medium is strictly
  ~ prohibited Proprietary and confidential.
  ~ Written by Johannes Fähndrich <faehndrich@gmail.com.com>,  2011
  ~
  -->

<!DOCTYPE head SYSTEM "heads.dtd">

<head number="466" name="Invisibility" origNum="#447." class="3" section="3" subSection="2" headGroup="37">
	<pos number="1" type="N.">
		<paragraph number="1" name="invisibility">
			<sg number="1">
				<word number="1">invisibility</word>
				<word number="2">invisibleness</word>
				<word number="3">nonappearance</word>
				<word number="4">imperceptibility</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="" posRef="adj.">indistinctness</word>
			</sg>
			<sg number="3">
				<word number="1">mystery</word>
				<word number="2">delitescence</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="concealment">
			<sg number="1">
				<word number="1" paraRef="concealment" headRef="554">concealment</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="latency" headRef="551">latency</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="2" type="VB.">
		<paragraph number="1" name="be invisible">
			<sg number="1">
				<word number="1" paraRef="" posRef="adj.">be invisible</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="hide" headRef="554">be hidden</word>
			</sg>
			<sg number="3">
				<word number="1" paraRef="hidden" headRef="554">lurk</word>
			</sg>
			<sg number="4">
				<word number="1">escape notice</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="render invisible">
			<sg number="1">
				<word number="1" paraRef="" posRef="adj.">render invisible</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="conceal" headRef="554">conceal</word>
			</sg>
			<sg number="3">
				<word number="1">put out of sight</word>
			</sg>
		</paragraph>
		<paragraph number="3" name="not see">
			<sg number="1">
				<word number="1" paraRef="be blind" headRef="461">not see</word>
			</sg>
			<sg number="2">
				<word number="1">lose sight of</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="3" type="ADJ.">
		<paragraph number="1" name="invisible">
			<sg number="1">
				<word number="1">invisible</word>
				<word number="2">imperceptible</word>
			</sg>
			<sg number="2">
				<word number="1">undiscernible</word>
				<word number="2">indiscernible</word>
			</sg>
			<sg number="3">
				<word number="1">unapparent</word>
				<word number="2">non-apparent</word>
			</sg>
			<sg number="4">
				<word number="1">out of sight</word>
				<word number="2">not in sight</word>
			</sg>
			<sg number="5">
				<word number="1">a perte de vue</word>
			</sg>
			<sg number="6">
				<word number="1">behind the scenes</word>
				<word number="2">behind the curtain</word>
			</sg>
			<sg number="7">
				<word number="1">viewless</word>
				<word number="2">sightless</word>
			</sg>
			<sg number="8">
				<word number="1">inconspicuous</word>
				<word number="2">unconspicuous</word>
			</sg>
			<sg number="9">
				<word number="1" paraRef="see" headRef="460">unseen</word>
			</sg>
			<sg number="10">
				<word number="1" paraRef="latent" headRef="551">covert</word>
			</sg>
			<sg number="11">
				<word number="1">eclipsed</word>
				<word number="2">under an eclipse</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="dim">
			<sg number="1">
				<word number="1" paraRef="faint" headRef="440">dim</word>
			</sg>
			<sg number="2">
				<word number="1">mysterious</word>
				<word number="2">dark</word>
				<word number="3">obscure</word>
				<word number="4">confused</word>
			</sg>
			<sg number="3">
				<word number="1">indistinct</word>
				<word number="2">indistinguishable</word>
			</sg>
			<sg number="4">
				<word number="1">shadowy</word>
				<word number="2">indefinite</word>
				<word number="3">undefined</word>
			</sg>
			<sg number="5">
				<word number="1">ill-defined</word>
				<word number="2">ill-marked</word>
			</sg>
			<sg number="6">
				<word number="1">blurred</word>
				<word number="2">fuzzy</word>
				<word number="3">out of focus</word>
			</sg>
			<sg number="7">
				<word number="1" paraRef="opaque" headRef="444">misty</word>
			</sg>
			<sg number="8">
				<word number="1">delitescent</word>
			</sg>
		</paragraph>
		<paragraph number="3" name="hidden">
			<sg number="1">
				<word number="1">hidden</word>
				<word number="2">obscured</word>
				<word number="3">covered</word>
				<word number="4" paraRef="concealed" headRef="554">veiled</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="6" type="PHR.">
		<paragraph number="1" name="full many a flower is born to blush unseen">
			<sg number="1">
				<word number="1">"full many a flower is born to blush unseen"</word>
			</sg>
		</paragraph>
	</pos>
</head>

=== Datenverlust/SemanticDecompositionExperiments/SemanticDistanceMeasures/ELKB/src/main/resources/roget_elkb/1911R/heads/head747.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!--
  ~ Copyright (C) Johannes Fähndrich - All Rights Reserved.
  ~ Unauthorized copying of this file, via any medium is strictly
  ~ prohibited Proprietary and confidential.
  ~ Written by Johannes Fähndrich <faehndrich@gmail.com.com>,  2011
  ~
  -->

<!DOCTYPE head SYSTEM "heads.dtd">
<?xml-stylesheet href="rogets.xsl" type="text/xsl" ?>

<head number="747" name="Retaliation" origNum="#718." class="6" section="4" subSection="1" headGroup="9">
	<pos number="1" type="N.">
		<paragraph number="1" name="retaliation">
			<sg number="1">
				<word number="1">retaliation</word>
				<word number="2">reprisal</word>
				<word number="3">retort</word>
				<word number="4">payback</word>
			</sg>
			<sg number="2">
				<word number="1">counter-stroke</word>
				<word number="2">counter-blast</word>
				<word number="3">counterplot</word>
				<word number="4">counter-project</word>
			</sg>
			<sg number="3">
				<word number="1">retribution</word>
				<word number="2">lex talionis</word>
			</sg>
			<sg number="4">
				<word number="1" paraRef="reciprocity" headRef="12">reciprocation</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="tit for tat">
			<sg number="1">
				<word number="1">tit for tat</word>
				<word number="2">give and take</word>
				<word number="3">blow for blow</word>
				<word number="4">quid pro quo</word>
				<word number="5">a Roland for an Oliver</word>
				<word number="6">measure for measure</word>
				<word number="7">diamond cut diamond</word>
				<word number="8">the biter bit</word>
				<word number="9">a game at which two can play</word>
			</sg>
			<sg number="2">
				<word number="1">reproof valiant</word>
				<word number="2">retort courteous</word>
			</sg>
		</paragraph>
		<paragraph number="3" name="recrimination">
			<sg number="1">
				<word number="1" paraRef="accusation" headRef="980">recrimination</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="revenge" headRef="960">revenge</word>
			</sg>
			<sg number="3">
				<word number="1" paraRef="compensation" headRef="32">compensation</word>
			</sg>
			<sg number="4">
				<word number="1" paraRef="recoil" headRef="288">reaction</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="2" type="VB.">
		<paragraph number="1" name="retaliate">
			<sg number="1">
				<word number="1">retaliate</word>
				<word number="2">retort</word>
				<word number="3">turn upon</word>
			</sg>
			<sg number="2">
				<word number="1">pay</word>
				<word number="2">pay off</word>
				<word number="3">pay back</word>
			</sg>
			<sg number="3">
				<word number="1">pay in one's own coin</word>
				<word number="2">pay in the same coin</word>
			</sg>
			<sg number="4">
				<word number="1">cap</word>
			</sg>
			<sg number="5">
				<word number="1" paraRef="reciprocate" headRef="155">reciprocate</word>
			</sg>
			<sg number="6">
				<word number="1">turn the tables upon</word>
				<word number="2">return the compliment</word>
			</sg>
			<sg number="7">
				<word number="1" paraRef="" posRef="n.">give a quid pro quo</word>
				<word number="2">give as much as one takes</word>
				<word number="3">give as good as one gets</word>
			</sg>
			<sg number="8">
				<word number="1">give and take</word>
				<word number="2">exchange fisticuffs</word>
			</sg>
			<sg number="9">
				<word number="1">be quits</word>
				<word number="2">be even with</word>
			</sg>
			<sg number="10">
				<word number="1">pay off old scores</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="serve one right">
			<sg number="1">
				<word number="1">serve one right</word>
				<word number="2">be hoist on one's own petard</word>
				<word number="3">throw a stone in one's own garden</word>
				<word number="4">catch a Tartar</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="3" type="ADJ.">
		<paragraph number="1" name="retaliating">
			<sg number="1">
				<word number="1" paraRef="" posRef="v.">retaliating</word>
			</sg>
			<sg number="2">
				<word number="1">retaliatory</word>
				<word number="2">retaliative</word>
			</sg>
			<sg number="3">
				<word number="1">talionic</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="4" type="ADV.">
		<paragraph number="1" name="in retaliation">
			<sg number="1">
				<word number="1">in retaliation</word>
			</sg>
			<sg number="2">
				<word number="1">en revanche</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="6" type="PHR.">
		<paragraph number="1" name="mutato nomine de te fabula narratur">
			<sg number="1">
				<word number="1">mutato nomine de te fabula narratur</word>
			</sg>
			<sg number="2">
				<word number="1">par pari refero</word>
			</sg>
			<sg number="3">
				<word number="1">tu quoque</word>
			</sg>
			<sg number="4">
				<word number="1">you're another</word>
			</sg>
			<sg number="5">
				<word number="1">suo sibi gladio hunc jugulo</word>
			</sg>
			<sg number="6">
				<word number="1">a beau jeu beau retour</word>
			</sg>
			<sg number="7">
				<word number="1">litem . . . lite resolvit</word>
			</sg>
		</paragraph>
	</pos>
</head>

=== Datenverlust/SemanticDecompositionExperiments/SemanticDistanceMeasures/Measures/src/test/resources/roget_elkb/1911X1/heads/head600.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!--
  ~ Copyright (C) Johannes Fähndrich - All Rights Reserved.
  ~ Unauthorized copying of this file, via any medium is strictly
  ~ prohibited Proprietary and confidential.
  ~ Written by Johannes Fähndrich <faehndrich@gmail.com.com>,  2011
  ~
  -->

<!DOCTYPE head SYSTEM "heads.dtd">
<?xml-stylesheet href="rogets.xsl" type="text/xsl" ?>

<head number="600" name="Vigor" origNum="#574." class="5" section="3" subSection="2" headGroup="10">
	<pos number="1" type="N.">
		<paragraph number="1" name="vigor">
			<sg number="1">
				<word number="1">vigor</word>
				<word number="2">power</word>
				<word number="3">force</word>
			</sg>
			<sg number="2">
				<word number="1">boldness</word>
				<word number="2" paraRef="" posRef="adj.">raciness</word>
			</sg>
			<sg number="3">
				<word number="1">intellectual</word>
				<word number="2">force</word>
			</sg>
			<sg number="4">
				<word number="1">spirit</word>
				<word number="2">point</word>
				<word number="3">antithesis</word>
				<word number="4">piquance</word>
				<word number="5">piquancy</word>
			</sg>
			<sg number="5">
				<word number="1">verve</word>
				<word number="2">glow</word>
				<word number="3">fire</word>
				<word number="4">warmth</word>
			</sg>
			<sg number="6">
				<word number="1">strong language</word>
			</sg>
			<sg number="7">
				<word number="1">gravity</word>
				<word number="2">sententiousness</word>
			</sg>
			<sg number="8">
				<word number="1">elevation</word>
				<word number="2">loftiness</word>
				<word number="3">sublimity</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="eloquence">
			<sg number="1">
				<word number="1">eloquence</word>
			</sg>
			<sg number="2">
				<word number="1">command of words</word>
				<word number="2">command of language</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="3" type="ADJ.">
		<paragraph number="1" name="vigorous">
			<sg number="1">
				<word number="1">vigorous</word>
				<word number="2">nervous</word>
				<word number="3">powerful</word>
				<word number="4">forcible</word>
				<word number="5">trenchant</word>
				<word number="6">incisive</word>
				<word number="7">impressive</word>
			</sg>
			<sg number="2">
				<word number="1">sensational</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="spirited">
			<sg number="1">
				<word number="1">spirited</word>
				<word number="2">lively</word>
				<word number="3">glowing</word>
				<word number="4">sparkling</word>
				<word number="5">racy</word>
				<word number="6">bold</word>
				<word number="7">slashing</word>
			</sg>
			<sg number="2">
				<word number="1">pungent</word>
				<word number="2">piquant</word>
				<word number="3">full of point</word>
				<word number="4">pointed</word>
				<word number="5">pithy</word>
				<word number="6">antithetical</word>
			</sg>
			<sg number="3">
				<word number="1">sententious</word>
			</sg>
		</paragraph>
		<paragraph number="3" name="lofty">
			<sg number="1">
				<word number="1">lofty</word>
				<word number="2">elevated</word>
				<word number="3">sublime</word>
			</sg>
			<sg number="2">
				<word number="1">eloquent</word>
			</sg>
			<sg number="3">
				<word number="1">vehement</word>
				<word number="2">petulant</word>
				<word number="3">impassioned</word>
				<word number="4" new="1">vociferous</word>
			</sg>
			<sg number="4">
				<word number="1">poetic</word>
			</sg>
			<sg number="5">
				<word number="1" new="1">fiery</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="4" type="ADV.">
		<paragraph number="1" name="in glowing terms">
			<sg number="1">
				<word number="1">in glowing terms</word>
				<word number="2">in good set terms</word>
				<word number="3">in no measured terms</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="6" type="PHR.">
		<paragraph number="1" name="thoughts that breath and words that burn">
			<sg number="1">
				<word number="1">"thoughts that breath and words that burn"</word>
			</sg>
		</paragraph>
	</pos>
</head>

=== Datenverlust/SemanticDecompositionExperiments/SemanticDistanceMeasures/Measures/src/test/resources/roget_elkb/1911R/heads/head131.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!--
  ~ Copyright (C) Johannes Fähndrich - All Rights Reserved.
  ~ Unauthorized copying of this file, via any medium is strictly
  ~ prohibited Proprietary and confidential.
  ~ Written by Johannes Fähndrich <faehndrich@gmail.com.com>,  2011
  ~
  -->

<!DOCTYPE head SYSTEM "heads.dtd">
<?xml-stylesheet href="rogets.xsl" type="text/xsl" ?>

<head number="131" name="Morning" origNum="#125." class="1" section="6" subSection="2" headGroup="6">
	<pos number="1" type="N.">
		<paragraph number="1" name="morning">
			<sg number="1">
				<word number="1">morning</word>
				<word number="2">morn</word>
				<word number="3">forenoon</word>
				<word number="4">a.m</word>
				<word number="5">prime</word>
				<word number="6">dawn</word>
				<word number="7">daybreak</word>
			</sg>
			<sg number="2">
				<word number="1">dayspring</word>
				<word number="2">foreday</word>
				<word number="3">sunup</word>
			</sg>
			<sg number="3">
				<word number="1">peep of day</word>
				<word number="2">break of day</word>
			</sg>
			<sg number="4">
				<word number="1">aurora</word>
			</sg>
			<sg number="5">
				<word number="1">first blush of the morning</word>
				<word number="2">first flush of the morning</word>
				<word number="3">prime of the morning</word>
			</sg>
			<sg number="6">
				<word number="1">twilight</word>
				<word number="2">crepuscule</word>
				<word number="3">sunrise</word>
			</sg>
			<sg number="7">
				<word number="1">cockcrow</word>
				<word number="2">cockcrowing</word>
			</sg>
			<sg number="8">
				<word number="1">the small hours</word>
				<word number="2">the wee hours of the morning</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="spring">
			<sg number="1">
				<word number="1">spring</word>
			</sg>
			<sg number="2">
				<word number="1">vernal equinox</word>
				<word number="2">first point of Aries</word>
			</sg>
		</paragraph>
		<paragraph number="3" name="noon">
			<sg number="1">
				<word number="1">noon</word>
			</sg>
			<sg number="2">
				<word number="1">midday</word>
				<word number="2">noonday</word>
			</sg>
			<sg number="3">
				<word number="1">noontide</word>
				<word number="2">meridian</word>
				<word number="3">prime</word>
			</sg>
			<sg number="4">
				<word number="1">nooning</word>
				<word number="2">noontime</word>
			</sg>
		</paragraph>
		<paragraph number="4" name="summer">
			<sg number="1">
				<word number="1">summer</word>
				<word number="2">midsummer</word>
			</sg>
		</paragraph>
		<paragraph number="5" name="railyard">
			<sg number="1">
				<word number="1" new="1">railyard</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="3" type="ADJ.">
		<paragraph number="1" name="matin">
			<sg number="1">
				<word number="1">matin</word>
				<word number="2">matutinal</word>
			</sg>
			<sg number="2">
				<word number="1">vernal</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="4" type="ADV.">
		<paragraph number="1" name="at sunrise">
			<sg number="1">
				<word number="1" paraRef="" posRef="n.">at sunrise</word>
			</sg>
			<sg number="2">
				<word number="1">with the sun</word>
				<word number="2">with the lark</word>
				<word number="3">"when the morning dawns"</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="6" type="PHR.">
		<paragraph number="1" name="at shut of evening flowers">
			<sg number="1">
				<word number="1">"at shut of evening flowers"</word>
			</sg>
			<sg number="2">
				<word number="1">entre chien et loup</word>
			</sg>
			<sg number="3">
				<word number="1">"flames in the forehead of the morning sky"</word>
			</sg>
			<sg number="4">
				<word number="1">"the breezy call of incense-breathing morn"</word>
			</sg>
		</paragraph>
	</pos>
</head>

=== Datenverlust/SemanticDecompositionExperiments/SemanticDistanceMeasures/ELKB/src/main/resources/roget_elkb/1911R/heads/head115.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!--
  ~ Copyright (C) Johannes Fähndrich - All Rights Reserved.
  ~ Unauthorized copying of this file, via any medium is strictly
  ~ prohibited Proprietary and confidential.
  ~ Written by Johannes Fähndrich <faehndrich@gmail.com.com>,  2011
  ~
  -->

<!DOCTYPE head SYSTEM "heads.dtd">
<?xml-stylesheet href="rogets.xsl" type="text/xsl" ?>

<head number="115" name="Course" origNum="#109." class="1" section="6" subSection="1" headGroup="3">
	<pos number="1" type="N.">
		<paragraph number="1" name="corridors of time">
			<sg number="1">
				<word number="1">corridors of time</word>
				<word number="2">sweep of time</word>
				<word number="3">vesta of time</word>
				<word number="4">course of time</word>
				<word number="5">progress of time</word>
				<word number="6">process of time</word>
				<word number="7">succession of time</word>
				<word number="8">lapse of time</word>
				<word number="9">flow of time</word>
				<word number="10">flux of time</word>
				<word number="11">stream of time</word>
				<word number="12">tract of time</word>
				<word number="13">current of time</word>
				<word number="14">tide of time</word>
				<word number="15">march of time</word>
				<word number="16">step of time</word>
				<word number="17">flight of time</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="duration" headRef="111">duration</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="aorist">
			<sg number="1">
				<word number="1">aorist</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="2" type="VB.">
		<paragraph number="1" name="elapse">
			<sg number="1">
				<word number="1">elapse</word>
				<word number="2">lapse</word>
				<word number="3">flow</word>
				<word number="4">run</word>
				<word number="5">proceed</word>
				<word number="6">advance</word>
				<word number="7">pass</word>
			</sg>
			<sg number="2">
				<word number="1">roll on</word>
				<word number="2">wear on</word>
				<word number="3">press on</word>
			</sg>
			<sg number="3">
				<word number="1">flit</word>
				<word number="2">fly</word>
				<word number="3">slip</word>
				<word number="4">slide</word>
				<word number="5">glide</word>
			</sg>
			<sg number="4">
				<word number="1">run its course</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="run out">
			<sg number="1">
				<word number="1">run out</word>
				<word number="2">expire</word>
			</sg>
			<sg number="2">
				<word number="1">go by</word>
				<word number="2">pass by</word>
			</sg>
			<sg number="3">
				<word number="1" paraRef="be past" headRef="128">be past</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="3" type="ADJ.">
		<paragraph number="1" name="elapsing">
			<sg number="1">
				<word number="1" paraRef="" posRef="v.">elapsing</word>
			</sg>
			<sg number="2">
				<word number="1">aoristic</word>
			</sg>
			<sg number="3">
				<word number="1">progressive</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="4" type="ADV.">
		<paragraph number="1" name="in due time">
			<sg number="1">
				<word number="1">in due time</word>
				<word number="2">in due  season</word>
			</sg>
			<sg number="2">
				<word number="1">in in due course</word>
				<word number="2">in due process</word>
				<word number="3">in the fullness of time</word>
			</sg>
			<sg number="3">
				<word number="1">in time</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="6" type="PHR.">
		<paragraph number="1" name="labitur et labetur">
			<sg number="1">
				<word number="1">labitur et labetur</word>
			</sg>
			<sg number="2">
				<word number="1">truditur dies die</word>
			</sg>
			<sg number="3">
				<word number="1">fugaces labuntur anni</word>
			</sg>
			<sg number="4">
				<word number="1">"tomorrow and tomorrow and tomorrow creeps in this petty pace from day to day"</word>
			</sg>
		</paragraph>
	</pos>
</head>

=== Datenverlust/SemanticDecompositionExperiments/SemanticDistanceMeasures/Measures/src/test/resources/roget_elkb/1911R/heads/head175.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!--
  ~ Copyright (C) Johannes Fähndrich - All Rights Reserved.
  ~ Unauthorized copying of this file, via any medium is strictly
  ~ prohibited Proprietary and confidential.
  ~ Written by Johannes Fähndrich <faehndrich@gmail.com.com>,  2011
  ~
  -->

<!DOCTYPE head SYSTEM "heads.dtd">
<?xml-stylesheet href="rogets.xsl" type="text/xsl" ?>

<head number="175" name="Productiveness" origNum="#168." class="1" section="8" subSection="3" headGroup="5">
	<pos number="1" type="N.">
		<paragraph number="1" name="productiveness">
			<sg number="1">
				<word number="1" paraRef="" posRef="adj.">productiveness</word>
			</sg>
			<sg number="2">
				<word number="1">fecundity</word>
				<word number="2">fertility</word>
				<word number="3">luxuriance</word>
				<word number="4">uberty|</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="pregnancy">
			<sg number="1">
				<word number="1">pregnancy</word>
				<word number="2">pullulation</word>
				<word number="3">fructification</word>
				<word number="4">multiplication</word>
				<word number="5">propagation</word>
				<word number="6">procreation</word>
			</sg>
			<sg number="2">
				<word number="1">superfetation</word>
			</sg>
		</paragraph>
		<paragraph number="3" name="milch cow">
			<sg number="1">
				<word number="1">milch cow</word>
				<word number="2">rabbit</word>
				<word number="3">hydra</word>
				<word number="4">warren</word>
				<word number="5">seed plot</word>
				<word number="6">land flowing with milk and honey</word>
			</sg>
			<sg number="2">
				<word number="1">second crop</word>
				<word number="2">aftermath</word>
			</sg>
			<sg number="3">
				<word number="1">aftercrop</word>
				<word number="2">aftergrowth</word>
			</sg>
			<sg number="4">
				<word number="1">arrish</word>
				<word number="2">eddish</word>
				<word number="3">rowen</word>
			</sg>
			<sg number="5">
				<word number="1">protoplasm</word>
			</sg>
			<sg number="6">
				<word number="1">fertilization</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="2" type="VB.">
		<paragraph number="1" name="make productive">
			<sg number="1">
				<word number="1" paraRef="" posRef="adj.">make productive</word>
			</sg>
			<sg number="2">
				<word number="1">fructify</word>
			</sg>
			<sg number="3">
				<word number="1">procreate</word>
				<word number="2">generate</word>
				<word number="3">fertilize</word>
				<word number="4">spermative</word>
				<word number="5">impregnate</word>
			</sg>
			<sg number="4">
				<word number="1">fecundate</word>
				<word number="2">fecundify</word>
			</sg>
			<sg number="5">
				<word number="1">teem</word>
				<word number="2">multiply</word>
			</sg>
			<sg number="6">
				<word number="1" paraRef="produce" headRef="168">produce</word>
			</sg>
			<sg number="7">
				<word number="1">conceive</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="3" type="ADJ.">
		<paragraph number="1" name="productive">
			<sg number="1">
				<word number="1">productive</word>
				<word number="2">prolific</word>
			</sg>
			<sg number="2">
				<word number="1">teeming</word>
				<word number="2">teemful</word>
			</sg>
			<sg number="3">
				<word number="1">fertile</word>
				<word number="2">fruitful</word>
				<word number="3">frugiferous</word>
				<word number="4">fruit-bearing</word>
				<word number="5" new="1">unprofessional</word>
			</sg>
			<sg number="4">
				<word number="1">fecund</word>
				<word number="2">luxuriant</word>
			</sg>
			<sg number="5">
				<word number="1">pregnant</word>
				<word number="2">uberous</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="procreant">
			<sg number="1">
				<word number="1">procreant</word>
				<word number="2">procreative</word>
			</sg>
			<sg number="2">
				<word number="1">generative</word>
				<word number="2">life-giving</word>
				<word number="3">spermatic</word>
			</sg>
			<sg number="3">
				<word number="1">multiparous</word>
			</sg>
			<sg number="4">
				<word number="1">omnific</word>
				<word number="2">propagable</word>
			</sg>
		</paragraph>
		<paragraph number="3" name="parturient">
			<sg number="1">
				<word number="1" paraRef="producing" headRef="168">parturient</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="useful" headRef="673">profitable</word>
			</sg>
		</paragraph>
	</pos>
</head>
