=== Datenverlust/SemanticDecompositionExperiments/SemanticDistanceMeasures/Measures/src/test/resources/roget_elkb/1911/heads/heads.dtd
<?xml version="1.0" encoding="iso-8859-1" ?>

<!--
  ~ Copyright (C) Johannes Fähndrich - All Rights Reserved.
  ~ Unauthorized copying of this file, via any medium is strictly
  ~ prohibited Proprietary and confidential.
  ~ Written by Johannes Fähndrich <faehndrich@gmail.com.com>,  2011
  ~
  -->

<!ELEMENT head (pos+)>
<!ATTLIST head number CDATA #REQUIRED name CDATA #REQUIRED origNum CDATA #REQUIRED class CDATA #REQUIRED section CDATA #REQUIRED subSection CDATA #REQUIRED headGroup CDATA #REQUIRED>

<!ELEMENT pos (paragraph+)>
<!ATTLIST pos number CDATA #REQUIRED type (N.|VB.|ADJ.|ADV.|INT.|PHR.|PREF.|PRON.) #REQUIRED>

<!ELEMENT paragraph (sg+)>
<!ATTLIST paragraph number CDATA #REQUIRED name CDATA #REQUIRED>

<!ELEMENT sg (word+)>
<!ATTLIST sg number CDATA #REQUIRED>

<!ELEMENT word (#PCDATA)>
<!ATTLIST word number CDATA #REQUIRED paraRef CDATA #IMPLIED posRef CDATA #IMPLIED headRef CDATA #IMPLIED>

=== Datenverlust/SemanticDecompositionExperiments/DataSet/src/main/resources/roget_elkb/1911R/heads/head311.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!--
  ~ Copyright (C) Johannes Fähndrich - All Rights Reserved.
  ~ Unauthorized copying of this file, via any medium is strictly
  ~ prohibited Proprietary and confidential.
  ~ Written by Johannes Fähndrich <faehndrich@gmail.com.com>,  2011
  ~
  -->

<!DOCTYPE head SYSTEM "heads.dtd">
<?xml-stylesheet href="rogets.xsl" type="text/xsl" ?>

<head number="311" name="Insertion" origNum="#300." class="2" section="4" subSection="4" headGroup="12">
	<pos number="1" type="N.">
		<paragraph number="1" name="insertion">
			<sg number="1">
				<word number="1">insertion</word>
				<word number="2">implantation</word>
				<word number="3">introduction</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="intervention" headRef="238">insinuation</word>
			</sg>
			<sg number="3">
				<word number="1" paraRef="" posRef="v.">planting</word>
			</sg>
			<sg number="4">
				<word number="1">injection</word>
				<word number="2">inoculation</word>
				<word number="3">importation</word>
				<word number="4">infusion</word>
			</sg>
			<sg number="5">
				<word number="1" paraRef="ingress" headRef="305">forcible ingress</word>
			</sg>
			<sg number="6">
				<word number="1">immersion</word>
			</sg>
			<sg number="7">
				<word number="1">submersion</word>
				<word number="2">submergence</word>
				<word number="3">dip</word>
				<word number="4">plunge</word>
			</sg>
			<sg number="8">
				<word number="1" paraRef="water" headRef="348">bath</word>
			</sg>
			<sg number="9">
				<word number="1" paraRef="interment" headRef="375">interment</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="clyster">
			<sg number="1">
				<word number="1">clyster</word>
				<word number="2">enema</word>
				<word number="3">glyster</word>
				<word number="4">lavage</word>
				<word number="5">lavement</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="2" type="VB.">
		<paragraph number="1" name="insert">
			<sg number="1">
				<word number="1">insert</word>
			</sg>
			<sg number="2">
				<word number="1">introduce</word>
				<word number="2">intromit</word>
			</sg>
			<sg number="3">
				<word number="1">put into</word>
				<word number="2">run into</word>
			</sg>
			<sg number="4">
				<word number="1">import</word>
			</sg>
			<sg number="5">
				<word number="1">inject</word>
			</sg>
			<sg number="6">
				<word number="1" paraRef="interject" headRef="238">interject</word>
			</sg>
			<sg number="7">
				<word number="1">infuse</word>
				<word number="2">instill</word>
				<word number="3">inoculate</word>
				<word number="4">impregnate</word>
				<word number="5">imbue</word>
				<word number="6">imbrue</word>
			</sg>
			<sg number="8">
				<word number="1" new="1">sponsor</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="graft">
			<sg number="1">
				<word number="1">graft</word>
				<word number="2">ingraft</word>
				<word number="3">bud</word>
				<word number="4">plant</word>
				<word number="5">implant</word>
			</sg>
			<sg number="2">
				<word number="1">dovetail</word>
			</sg>
		</paragraph>
		<paragraph number="3" name="obtrude">
			<sg number="1">
				<word number="1">obtrude</word>
			</sg>
			<sg number="2">
				<word number="1">thrust in</word>
				<word number="2">stick in</word>
				<word number="3">ram in</word>
				<word number="4">stuff in</word>
				<word number="5">tuck in</word>
				<word number="6">press</word>
				<word number="7">in</word>
				<word number="8">drive in</word>
				<word number="9">pop in</word>
				<word number="10">whip in</word>
				<word number="11">drop in</word>
				<word number="12">put in</word>
			</sg>
			<sg number="3">
				<word number="1">impact</word>
			</sg>
			<sg number="4">
				<word number="1" paraRef="hole" headRef="271">empierce|</word>
			</sg>
		</paragraph>
		<paragraph number="4" name="imbed">
			<sg number="1">
				<word number="1">imbed</word>
			</sg>
			<sg number="2">
				<word number="1">immerse</word>
				<word number="2">immerge</word>
				<word number="3">merge</word>
			</sg>
			<sg number="3">
				<word number="1">bathe</word>
				<word number="2" paraRef="water" headRef="348">soak</word>
			</sg>
			<sg number="4">
				<word number="1">dip</word>
				<word number="2" paraRef="plunge" headRef="321">plunge</word>
			</sg>
		</paragraph>
		<paragraph number="5" name="bury">
			<sg number="1">
				<word number="1" paraRef="inter" headRef="375">bury</word>
			</sg>
		</paragraph>
		<paragraph number="6" name="insert itself">
			<sg number="1">
				<word number="1">insert itself</word>
			</sg>
			<sg number="2">
				<word number="1">plunge in medias res</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="3" type="ADJ.">
		<paragraph number="1" name="inserted">
			<sg number="1">
				<word number="1" paraRef="" posRef="v.">inserted</word>
			</sg>
		</paragraph>
	</pos>
</head>

=== Datenverlust/SemanticDecompositionExperiments/SemanticDistanceMeasures/ELKB/src/main/resources/roget_elkb/1911/heads/head683.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!--
  ~ Copyright (C) Johannes Fähndrich - All Rights Reserved.
  ~ Unauthorized copying of this file, via any medium is strictly
  ~ prohibited Proprietary and confidential.
  ~ Written by Johannes Fähndrich <faehndrich@gmail.com.com>,  2011
  ~
  -->

<!DOCTYPE head SYSTEM "heads.dtd">

<head number="683" name="Health" origNum="#654." class="6" section="2" subSection="2" headGroup="16">
	<pos number="1" type="N.">
		<paragraph number="1" name="health">
			<sg number="1">
				<word number="1">health</word>
				<word number="2">sanity</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="" posRef="adj.">soundness</word>
			</sg>
			<sg number="3">
				<word number="1">vigor</word>
			</sg>
			<sg number="4">
				<word number="1">good health</word>
				<word number="2">perfect health</word>
				<word number="3">excellent health</word>
				<word number="4">rude health</word>
				<word number="5">robust health</word>
			</sg>
			<sg number="5">
				<word number="1">bloom</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="mens sana in corpore sano">
			<sg number="1">
				<word number="1">mens sana in corpore sano</word>
			</sg>
			<sg number="2">
				<word number="1">Hygeia</word>
			</sg>
			<sg number="3">
				<word number="1">incorruption</word>
				<word number="2">incorruptibility</word>
			</sg>
			<sg number="4">
				<word number="1">good state of health</word>
				<word number="2">clean bill of health</word>
			</sg>
			<sg number="5">
				<word number="1">eupepsia</word>
			</sg>
			<sg number="6">
				<word number="1">euphoria</word>
				<word number="2">euphory</word>
			</sg>
			<sg number="7">
				<word number="1">St Anthony's fire</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="2" type="VB.">
		<paragraph number="1" name="be in health">
			<sg number="1">
				<word number="1" paraRef="" posRef="adj.">be in health</word>
				<word number="2">flourish</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="keep body and soul together">
			<sg number="1">
				<word number="1">keep body and soul together</word>
				<word number="2">keep on one's legs</word>
			</sg>
			<sg number="2">
				<word number="1">enjoy good health</word>
				<word number="2">enjoy a good state of health</word>
			</sg>
			<sg number="3">
				<word number="1">have a clean bill of health</word>
			</sg>
		</paragraph>
		<paragraph number="3" name="return to health">
			<sg number="1">
				<word number="1">return to health</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="recover" headRef="689">recover</word>
			</sg>
			<sg number="3">
				<word number="1" paraRef="improve" headRef="687">get better</word>
			</sg>
			<sg number="4">
				<word number="1">take a new lease of life</word>
				<word number="2">fresh lease of life</word>
			</sg>
			<sg number="5">
				<word number="1">recruit</word>
			</sg>
			<sg number="6">
				<word number="1">restore to health</word>
			</sg>
			<sg number="7">
				<word number="1" paraRef="restore" headRef="689">cure</word>
			</sg>
			<sg number="8">
				<word number="1">tinker</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="3" type="ADJ.">
		<paragraph number="1" name="healthy">
			<sg number="1">
				<word number="1">healthy</word>
				<word number="2">healthful</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="" posRef="n.">in health</word>
			</sg>
			<sg number="3">
				<word number="1">well</word>
				<word number="2">sound</word>
				<word number="3">hearty</word>
				<word number="4">hale</word>
				<word number="5">fresh</word>
				<word number="6">green</word>
				<word number="7">whole</word>
			</sg>
			<sg number="4">
				<word number="1">florid</word>
				<word number="2">flush</word>
				<word number="3">hardy</word>
				<word number="4">stanch</word>
				<word number="5">staunch</word>
				<word number="6">brave</word>
				<word number="7">robust</word>
				<word number="8">vigorous</word>
				<word number="9">weatherproof</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="unscathed">
			<sg number="1">
				<word number="1">unscathed</word>
				<word number="2">uninjured</word>
				<word number="3">unmaimed</word>
				<word number="4">unmarred</word>
				<word number="5">untainted</word>
			</sg>
			<sg number="2">
				<word number="1">sound of wind and limb</word>
				<word number="2">safe and sound</word>
			</sg>
		</paragraph>
		<paragraph number="3" name="on one's legs">
			<sg number="1">
				<word number="1">on one's legs</word>
			</sg>
			<sg number="2">
				<word number="1">sound as a roach</word>
				<word number="2">sound as a bell</word>
			</sg>
			<sg number="3">
				<word number="1">fresh as a daisy</word>
				<word number="2">fresh as a rose</word>
				<word number="3">fresh as April</word>
			</sg>
			<sg number="4">
				<word number="1">hearty as a buck</word>
			</sg>
			<sg number="5">
				<word number="1">in fine feather</word>
				<word number="2">in high feather</word>
			</sg>
			<sg number="6">
				<word number="1">in good case</word>
				<word number="2">in full bloom</word>
			</sg>
			<sg number="7">
				<word number="1">pretty bobbish</word>
				<word number="2">tolerably well</word>
				<word number="3">as well as can be expected</word>
			</sg>
		</paragraph>
		<paragraph number="4" name="sanitary">
			<sg number="1">
				<word number="1" paraRef="healthful" headRef="685">sanitary</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="remedial" headRef="691">sanatory</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="6" type="PHR.">
		<paragraph number="1" name="health that snuffs the morning air">
			<sg number="1">
				<word number="1">"health that snuffs the morning air"</word>
			</sg>
			<sg number="2">
				<word number="1">non est vivere sed valere vita</word>
			</sg>
		</paragraph>
	</pos>
</head>

=== Datenverlust/SemanticDecompositionExperiments/SemanticDistanceMeasures/Measures/src/test/resources/roget_elkb/1911X1/heads/head893.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!--
  ~ Copyright (C) Johannes Fähndrich - All Rights Reserved.
  ~ Unauthorized copying of this file, via any medium is strictly
  ~ prohibited Proprietary and confidential.
  ~ Written by Johannes Fähndrich <faehndrich@gmail.com.com>,  2011
  ~
  -->

<!DOCTYPE head SYSTEM "heads.dtd">
<?xml-stylesheet href="rogets.xsl" type="text/xsl" ?>

<head number="893" name="Fop" origNum="#854." class="8" section="2" subSection="2" headGroup="6">
	<pos number="1" type="N.">
		<paragraph number="1" name="fop">
			<sg number="1">
				<word number="1">fop</word>
				<word number="2">fine gentleman</word>
			</sg>
			<sg number="2">
				<word number="1">swell</word>
			</sg>
			<sg number="3">
				<word number="1">dandy</word>
				<word number="2">dandiprat!</word>
			</sg>
			<sg number="4">
				<word number="1">exquisite</word>
				<word number="2">coxcomb</word>
				<word number="3">beau</word>
				<word number="4">macaroni</word>
				<word number="5">blade</word>
				<word number="6">blood</word>
				<word number="7">buck</word>
				<word number="8">man about town</word>
				<word number="9">fast man</word>
			</sg>
			<sg number="5">
				<word number="1">fribble</word>
				<word number="2">milliner!</word>
			</sg>
			<sg number="6">
				<word number="1">Jemmy Jessamy!</word>
				<word number="2">carpet knight</word>
			</sg>
			<sg number="7">
				<word number="1">masher</word>
				<word number="2">dude</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="fine lady">
			<sg number="1">
				<word number="1">fine lady</word>
				<word number="2">coquette</word>
			</sg>
			<sg number="2">
				<word number="1">flirt</word>
				<word number="2">vamp</word>
			</sg>
		</paragraph>
	</pos>
</head>

=== Datenverlust/SemanticDecompositionExperiments/SemanticDistanceMeasures/ELKB/src/main/resources/roget_elkb/1911R/heads/head996.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!--
  ~ Copyright (C) Johannes Fähndrich - All Rights Reserved.
  ~ Unauthorized copying of this file, via any medium is strictly
  ~ prohibited Proprietary and confidential.
  ~ Written by Johannes Fähndrich <faehndrich@gmail.com.com>,  2011
  ~
  -->

<!DOCTYPE head SYSTEM "heads.dtd">
<?xml-stylesheet href="rogets.xsl" type="text/xsl" ?>

<head number="996" name="Intemperance" origNum="#954." class="8" section="4" subSection="4" headGroup="1">
	<pos number="1" type="N.">
		<paragraph number="1" name="intemperance">
			<sg number="1">
				<word number="1">intemperance</word>
			</sg>
			<sg number="2">
				<word number="1">sensuality</word>
				<word number="2">animalism</word>
				<word number="3">carnality</word>
			</sg>
			<sg number="3">
				<word number="1">tragalism</word>
			</sg>
			<sg number="4">
				<word number="1">pleasure</word>
			</sg>
			<sg number="5">
				<word number="1">effeminacy</word>
				<word number="2">silkiness</word>
			</sg>
			<sg number="6">
				<word number="1">luxury</word>
				<word number="2">luxuriousness</word>
			</sg>
			<sg number="7">
				<word number="1">lap of pleasure</word>
				<word number="2">lap of luxury</word>
			</sg>
			<sg number="8">
				<word number="1">free living</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="indulgence">
			<sg number="1">
				<word number="1">indulgence</word>
			</sg>
			<sg number="2">
				<word number="1">high living</word>
				<word number="2">wild living</word>
				<word number="3">inabstinence</word>
				<word number="4">self- indulgence</word>
			</sg>
			<sg number="3">
				<word number="1" paraRef="" posRef="adj.">voluptuousness</word>
			</sg>
			<sg number="4">
				<word number="1">epicurism</word>
				<word number="2">epicureanism</word>
			</sg>
			<sg number="5">
				<word number="1">sybaritism</word>
			</sg>
			<sg number="6">
				<word number="1">drug habit</word>
			</sg>
		</paragraph>
		<paragraph number="3" name="dissipation">
			<sg number="1">
				<word number="1">dissipation</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="" posRef="adj.">licentiousness</word>
			</sg>
			<sg number="3">
				<word number="1">debauchery</word>
			</sg>
			<sg number="4">
				<word number="1">crapulence</word>
			</sg>
		</paragraph>
		<paragraph number="4" name="revels">
			<sg number="1">
				<word number="1">revels</word>
				<word number="2">revelry</word>
			</sg>
			<sg number="2">
				<word number="1">debauch</word>
				<word number="2">carousal</word>
				<word number="3">jollification</word>
				<word number="4">drinking bout</word>
				<word number="5">wassail</word>
				<word number="6">saturnalia</word>
				<word number="7">orgies</word>
			</sg>
			<sg number="3">
				<word number="1">excess</word>
				<word number="2">too much</word>
			</sg>
		</paragraph>
		<paragraph number="5" name="Circean cup">
			<sg number="1">
				<word number="1">Circean cup</word>
			</sg>
		</paragraph>
		<paragraph number="6" name="bhang">
			<sg number="1">
				<word number="1">bhang</word>
				<word number="2">hashish</word>
				<word number="3">marijuana</word>
				<word number="4">pot</word>
				<word number="5">hemp</word>
				<word number="6">grass</word>
			</sg>
			<sg number="2">
				<word number="1">opium</word>
				<word number="2">cocaine</word>
				<word number="3">morphine</word>
				<word number="4">heroin</word>
				<word number="5" new="1">subkingdom</word>
				<word number="6" new="1">allemande</word>
				<word number="7" new="1">chyme</word>
				<word number="8" new="1">zapovedniks</word>
				<word number="9" new="1">trachomatis</word>
			</sg>
			<sg number="3">
				<word number="1">LSD</word>
				<word number="2">lysergic acid diethylamide</word>
			</sg>
			<sg number="4">
				<word number="1">phencyclidine</word>
				<word number="2">angel dust</word>
				<word number="3">PCP</word>
			</sg>
			<sg number="5">
				<word number="1">barbiturates</word>
			</sg>
			<sg number="6">
				<word number="1">amphetamines</word>
				<word number="2">speed</word>
			</sg>
			<sg number="7">
				<word number="1" new="1">syndicated</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="2" type="VB.">
		<paragraph number="1" name="be intemperate">
			<sg number="1">
				<word number="1" paraRef="" posRef="adj.">be intemperate</word>
			</sg>
			<sg number="2">
				<word number="1">indulge</word>
				<word number="2">exceed</word>
			</sg>
			<sg number="3">
				<word number="1">live well</word>
				<word number="2">live high</word>
				<word number="3">live high on the fat of the land</word>
				<word number="4">live it up</word>
				<word number="5">live high on the hog</word>
			</sg>
			<sg number="4">
				<word number="1" paraRef="" posRef="n.">give a loose to indulgence</word>
			</sg>
			<sg number="5">
				<word number="1" paraRef="" posRef="n.">wallow in voluptuousness</word>
			</sg>
			<sg number="6">
				<word number="1">plunge into dissipation</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="revel">
			<sg number="1">
				<word number="1">revel</word>
			</sg>
			<sg number="2">
				<word number="1">rake</word>
				<word number="2">live hard</word>
				<word number="3">run riot</word>
				<word number="4">sow one's wild oats</word>
			</sg>
			<sg number="3">
				<word number="1">slake one's appetite</word>
				<word number="2">slake one's thirst</word>
			</sg>
			<sg number="4">
				<word number="1">swill</word>
			</sg>
			<sg number="5">
				<word number="1">pamper</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="3" type="ADJ.">
		<paragraph number="1" name="intemperate">
			<sg number="1">
				<word number="1">intemperate,inabstinent</word>
			</sg>
			<sg number="2">
				<word number="1">sensual</word>
				<word number="2">self-indulgent</word>
			</sg>
			<sg number="3">
				<word number="1">voluptuous</word>
				<word number="2">luxurious</word>
				<word number="3">licentious</word>
				<word number="4">wild</word>
				<word number="5">dissolute</word>
				<word number="6">rakish</word>
				<word number="7">fast</word>
				<word number="8">debauched</word>
				<word number="9" new="1">extraverted</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="brutish">
			<sg number="1">
				<word number="1">brutish</word>
				<word number="2">crapulous</word>
				<word number="3">swinish</word>
				<word number="4">piggish</word>
			</sg>
		</paragraph>
		<paragraph number="3" name="Paphian">
			<sg number="1">
				<word number="1">Paphian</word>
				<word number="2">Epicurean</word>
				<word number="3">Sybaritical</word>
			</sg>
			<sg number="2">
				<word number="1">bred in the lap of luxury</word>
				<word number="2">nursed in the lap of luxury</word>
			</sg>
			<sg number="3">
				<word number="1">indulged</word>
				<word number="2">pampered</word>
			</sg>
			<sg number="4">
				<word number="1">full-fed</word>
				<word number="2">high-fed</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="6" type="PHR.">
		<paragraph number="1" name="being full of supper and distempering draughts">
			<sg number="1">
				<word number="1">"being full of supper and distempering draughts"</word>
			</sg>
		</paragraph>
	</pos>
</head>

=== Datenverlust/SemanticDecompositionExperiments/DataSet/src/main/resources/roget_elkb/1911R/heads/head970.xml
<?xml version="1.0" encoding="iso-8859-1" ?>
<!--
  ~ Copyright (C) Johannes Fähndrich - All Rights Reserved.
  ~ Unauthorized copying of this file, via any medium is strictly
  ~ prohibited Proprietary and confidential.
  ~ Written by Johannes Fähndrich <faehndrich@gmail.com.com>,  2011
  ~
  -->

<!DOCTYPE head SYSTEM "heads.dtd">
<?xml-stylesheet href="rogets.xsl" type="text/xsl" ?>

<head number="970" name="Respect" origNum="#928." class="8" section="4" subSection="2" headGroup="1">
	<pos number="1" type="N.">
		<paragraph number="1" name="respect">
			<sg number="1">
				<word number="1">respect</word>
				<word number="2">regard</word>
				<word number="3">consideration</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="courtesy" headRef="933">courtesy</word>
			</sg>
			<sg number="3">
				<word number="1">attention</word>
				<word number="2">deference</word>
				<word number="3">reverence</word>
				<word number="4">honor</word>
				<word number="5">esteem</word>
				<word number="6">estimation</word>
				<word number="7">veneration</word>
				<word number="8">admiration</word>
				<word number="9" new="1">porteos</word>
				<word number="10" new="1">streambed</word>
			</sg>
			<sg number="4">
				<word number="1" paraRef="approbation" headRef="973">approbation</word>
			</sg>
			<sg number="5">
				<word number="1" new="1">espaoles</word>
			</sg>
			<sg number="6">
				<word number="1" new="1">vesture</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="homage">
			<sg number="1">
				<word number="1">homage</word>
				<word number="2">fealty</word>
				<word number="3">obeisance</word>
				<word number="4">genuflection</word>
				<word number="5">kneeling prostration</word>
			</sg>
			<sg number="2">
				<word number="1" paraRef="obsequiousness" headRef="925">obsequiousness</word>
			</sg>
			<sg number="3">
				<word number="1">salaam</word>
				<word number="2">kowtow</word>
				<word number="3">bow</word>
				<word number="4">presenting arms</word>
				<word number="5">salute</word>
			</sg>
		</paragraph>
		<paragraph number="3" name="respects">
			<sg number="1">
				<word number="1">respects</word>
				<word number="2">regards</word>
				<word number="3">duty</word>
				<word number="4">devoirs</word>
				<word number="5">egards</word>
			</sg>
		</paragraph>
		<paragraph number="4" name="devotion">
			<sg number="1">
				<word number="1" paraRef="piety" headRef="1031">devotion</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="2" type="VB.">
		<paragraph number="1" name="respect">
			<sg number="1">
				<word number="1">respect</word>
				<word number="2">regard</word>
			</sg>
			<sg number="2">
				<word number="1">revere</word>
				<word number="2">reverence</word>
			</sg>
			<sg number="3">
				<word number="1">hold in reverence</word>
				<word number="2">honor</word>
				<word number="3">venerate</word>
				<word number="4">hallow</word>
			</sg>
			<sg number="4">
				<word number="1" paraRef="approve" headRef="973">esteem</word>
			</sg>
			<sg number="5">
				<word number="1">think much of</word>
			</sg>
			<sg number="6">
				<word number="1">entertain respect for</word>
				<word number="2">bear respect for</word>
			</sg>
			<sg number="7">
				<word number="1">look up to</word>
				<word number="2">defer to</word>
			</sg>
			<sg number="8">
				<word number="1">have a high opinion of</word>
				<word number="2">hold a high opinion of</word>
			</sg>
			<sg number="9">
				<word number="1">pay attention</word>
				<word number="2" paraRef="" posRef="n.">pay respect</word>
			</sg>
			<sg number="10">
				<word number="1">do honor to</word>
				<word number="2">render honor to</word>
			</sg>
			<sg number="11">
				<word number="1">do the honors</word>
				<word number="2">hail</word>
			</sg>
			<sg number="12">
				<word number="1" paraRef="show courtesy" headRef="933">show courtesy</word>
			</sg>
			<sg number="13">
				<word number="1">salute</word>
				<word number="2">present arms</word>
			</sg>
			<sg number="14">
				<word number="1">do homage to</word>
				<word number="2">pay homage to</word>
			</sg>
			<sg number="15">
				<word number="1">pay tribute to</word>
				<word number="2">kneel to</word>
				<word number="3">bow to</word>
				<word number="4">bend the knee to</word>
			</sg>
			<sg number="16">
				<word number="1">fall down before</word>
				<word number="2">prostrate oneself</word>
				<word number="3">kiss the hem of one's garment</word>
			</sg>
			<sg number="17">
				<word number="1" paraRef="worship" headRef="1034">worship</word>
			</sg>
			<sg number="18">
				<word number="1" new="1">disambiguate</word>
			</sg>
			<sg number="19">
				<word number="1" new="1">parrot</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="keep one's distance">
			<sg number="1">
				<word number="1">keep one's distance</word>
				<word number="2">make room</word>
				<word number="3">observe due decorum</word>
				<word number="4">stand upon ceremony</word>
			</sg>
		</paragraph>
		<paragraph number="3" name="command respect">
			<sg number="1">
				<word number="1">command respect</word>
				<word number="2">inspire respect</word>
			</sg>
			<sg number="2">
				<word number="1">awe</word>
				<word number="2">inspire awe</word>
				<word number="3">impose</word>
				<word number="4">overawe</word>
				<word number="5">dazzle</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="3" type="ADJ.">
		<paragraph number="1" name="respecting">
			<sg number="1">
				<word number="1" paraRef="" posRef="v.">respecting</word>
			</sg>
			<sg number="2">
				<word number="1">respectful</word>
				<word number="2">deferential</word>
				<word number="3">decorous</word>
				<word number="4">reverential</word>
				<word number="5">obsequious</word>
				<word number="6">ceremonious</word>
				<word number="7">bareheaded</word>
				<word number="8">cap in hand</word>
				<word number="9">on one's knees</word>
			</sg>
			<sg number="3">
				<word number="1" paraRef="servile" headRef="925">prostrate</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="respected">
			<sg number="1">
				<word number="1" paraRef="" posRef="v.">respected</word>
			</sg>
			<sg number="2">
				<word number="1">in high esteem</word>
				<word number="2">in high estimation</word>
			</sg>
			<sg number="3">
				<word number="1">time-honored</word>
				<word number="2">venerable</word>
				<word number="3">emeritus</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="4" type="ADV.">
		<paragraph number="1" name="in deference to">
			<sg number="1">
				<word number="1">in deference to</word>
			</sg>
			<sg number="2">
				<word number="1">with all respect</word>
				<word number="2">with all due respect</word>
				<word number="3">with due respect</word>
				<word number="4">with the highest respect</word>
			</sg>
			<sg number="3">
				<word number="1">with submission</word>
			</sg>
		</paragraph>
		<paragraph number="2" name="saving your grace">
			<sg number="1">
				<word number="1">saving your grace</word>
				<word number="2">saving your presence</word>
			</sg>
			<sg number="2">
				<word number="1">salva sit reverentia</word>
			</sg>
			<sg number="3">
				<word number="1">pace tanti nominis</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="5" type="INT.">
		<paragraph number="1" name="hail">
			<sg number="1">
				<word number="1">hail!</word>
				<word number="2">all hail!</word>
				<word number="3">esto perpetua!</word>
				<word number="4">may your shadow never be less!</word>
			</sg>
		</paragraph>
	</pos>
	<pos number="6" type="PHR.">
		<paragraph number="1" name="and pluck up drowned honor by the locks">
			<sg number="1">
				<word number="1">"and pluck up drowned honor by the locks"</word>
			</sg>
			<sg number="2">
				<word number="1">"his honor rooted in dishonor stood"</word>
			</sg>
			<sg number="3">
				<word number="1">"honor pricks me on"</word>
			</sg>
		</paragraph>
	</pos>
</head>
